#!/usr/bin/env php
<?php 
## fp2sh - make some shell scripts to run flatpaks by their short name
##         IN THE CURRENT DIR on toppa whatever else may be here

$gr = "grep -i --no-filename 'exec=' " . 
      "/var/lib/flatpak/exports/share/applications/*.desktop";
$cmd = [];   $exe = [];
foreach (explode ("\n", `$gr`) as $s) {
   $p = strpos ($s, '--command=');
   if ($p == false)  continue;  # prob last empty line

   $c = substr ($s, $p+10);
   $e = strpos ($c, ' ');
   if ($e === false)  echo "can't find end of command in $c\n";
   else {
      $c = substr ($c, 0, $e);
      if (substr ($c, 0, 9) == '/app/bin/')  $c = substr ($c, 9);
      if (strpos ($c, '.') !== false) {
         $a = explode ('.', $c);
         $c = $a [COUNT ($a)-1];
      }
      $c = trim (strtolower ($c));
      if (in_array ($c, $cmd)) {
         for ($n = 1;  in_array ("$c$n", $cmd);  $n++)  ;
         $c .= $n;
      }
      $cmd[] = $c;   $exe[] = $s;
   }
}
foreach ($cmd as $i => $c) {  # kill Exec=
   file_put_contents ($c, substr ($exe [$i], 5). "\n");
   system ("chmod 777 $c");   # consider "$@" for args
}
